In [1]:
import cv2
import numpy as np
import os

In [6]:
import cv2

cap = cv2.VideoCapture(r"C:\Users\GillA\Desktop\University\test.mp4")
ret, frame = cap.read()

i = 0

while(1):
    ret, frame = cap.read()
    if cv2.waitKey(1) & 0xFF == ord('q') or ret==False :
        cap.release()
        cv2.destroyAllWindows()
        break
    if i%5 == 0:
        cv2.imwrite("raw/2003Cavs_2_frame" + str(i) + '.jpg',frame)
    i +=1

In [4]:
cap.read()

(False, None)

# Cropping

In [30]:
for i in list(os.listdir("raw")):

    img = cv2.imread('raw/' + i)

    # Cropping an image
    cropped_image = img[:, 253:1920-253]

    # Save the cropped image
    cv2.imwrite("cropped/" + i, cropped_image)

In [10]:
img = cv2.imread('raw/2003Cavs_2_frame0.jpg')
print(img.shape)
cropped_image = img[:, 253:1920-253]
cv2.imwrite("cropped/2003Cavs_2_frame0.jpg", cropped_image)

(1080, 1920, 3)


True

In [9]:
print(cropped_image)

[[[ 6  6 12]
  [ 7  6 15]
  [26 25 34]
  ...
  [ 3  0  2]
  [ 3  0  2]
  [ 3  0  2]]

 [[ 6  6 12]
  [ 8  7 16]
  [28 27 36]
  ...
  [ 3  0  2]
  [ 3  0  2]
  [ 3  0  2]]

 [[ 6  6 12]
  [ 7  6 15]
  [28 27 36]
  ...
  [ 3  0  2]
  [ 3  0  2]
  [ 3  0  2]]

 ...

 [[ 8  7  9]
  [22 21 23]
  [29 28 30]
  ...
  [ 1  0  2]
  [ 1  0  2]
  [ 1  0  2]]

 [[ 6  5  7]
  [19 18 20]
  [26 25 27]
  ...
  [ 0  0  1]
  [ 0  0  1]
  [ 0  0  1]]

 [[ 4  3  5]
  [17 16 18]
  [24 23 25]
  ...
  [ 0  0  1]
  [ 0  0  1]
  [ 0  0  1]]]
